### ISSUE TITLE
Chapter 4 exercises still using `%>%`

### ISSUE THREAD

**Issue by AmeliaMN** [mdsr-book/mdsr2exercises#45]
For example, see "Problem 2 (Easy): We’ll be working with the `babynames` data frame in the `babynames` package. To remind you what `babynames` looks like, here are a few rows." The parts of the question with incorrect pipelines have the magrittr pipe, like `babynames %>% select(n > 100)`. Problems 3 and 5 also have the `%>%` pipe.

**Comment by nicholasjhorton** [comment]
Oddly I pushed a change at 2pm ET today (which won't necessarily show up unless we tweak the DESCRIPTION for mdsr2exercises and make a change to the mdsr3 repo). But this is (modest) evidence of a good faith effort. 

https://github.com/mdsr-book/mdsr2exercises/commit/a660bf762362ce778abfb50aa88af98e2180b2e0

**Comment by beanumber** [comment]
```
grep -l '%>%' *.Rmd | xargs sed -i -E "s/%>%/|>/g"
```
