### ISSUE TITLE
Chapter 3 exercise suggestions

### ISSUE THREAD

**Issue by willwerscheid** [mdsr-book/mdsr2exercises#47]
Here are some "hints" I provided to students for assigned exercises from chapter 3. The first and last should be treated as bugs I think. 3.8 looks pretty bad without removing the legend. Probably don't need to include my "hint" for 3.7.

3.2 and 3.8. Use the storms dataset from the nasaweather package.

3.7. For information on how to use faceting and add regression lines, see MDSR section 3.2.2 (use CTRL+F to find the relevant paragraphs).

3.8. I suggest removing the color legend using guides(color = "none").

3.9. I think the sentence "Add regression lines to all of your facets" is supposed to be in part b).

**Comment by beanumber** [comment]
Thanks @willwerscheid !
